#!/usr/bin/env zsh
app=$1

if ! which stow > /dev/null; then
    echo "Install gnu stow before using this function"
    exit 1
fi

echo "Stowing dotfiles for $app"
stow --dir=apps --target=$HOME --ignore=install.zsh -R $app
