#!/usr/bin/env zsh
alias colourify="grc -es --colour=auto"

alias as='colourify as'
alias configure='colourify ./configure'
alias df='colourify df'
alias diff='colourify diff'
alias dig='colourify dig'
alias g++='colourify g++'
alias gas='colourify gas'
alias gcc='colourify gcc'
alias head='colourify head'
alias ifconfig='colourify ifconfig'
alias ld='colourify ld'
alias ls='colourify ls'
alias make='colourify make'
alias mount='colourify mount'
alias mtr='colourify mtr'
alias netstat='colourify netstat'
alias ping='colourify ping'
alias ps='colourify ps'
alias tail='colourify tail'
alias traceroute='colourify /usr/sbin/traceroute'
